services:
  db:
    platform: linux/amd64
    image: mysql:8.0
    restart: always

  backend:
    platform: linux/amd64
    image: tcuprojectpulse.azurecr.io/project-pulse-backend:latest
    expose:
      - "8080"
    depends_on:
      - db
    restart: always

  frontend:
    platform: linux/amd64
    image: tcuprojectpulse.azurecr.io/project-pulse-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
