services:
  backend:
    platform: linux/amd64
    image: ${ACR_NAME}.azurecr.io/project-pulse-backend:latest
    expose:
      - "8080"
    environment:
      - SECURITY_JWT_SECRET=${SECURITY_JWT_SECRET}
    restart: always

  frontend:
    platform: linux/amd64
    image: ${ACR_NAME}.azurecr.io/project-pulse-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
