spring:
  application:
    name: project-pulse

  datasource:
    url: jdbc:h2:mem:projectpulsedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

app:
  base-url: http://localhost:3000
  admin-email: admin@tcu.edu
  admin-name: Admin User
